// Manual screenshots: actual production UI, isolated demonstration bridge.
const fs=require('node:fs'),path=require('node:path')
const {chromium}=require(path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))
const out=path.join(__dirname,'../output/pdf/Stock-King-v2.4.2-图文说明书/images')
const qa=fs.readFileSync(path.join(__dirname,'research-experience-ui-qa.cjs'),'utf8').replace(/\r\n/g,'\n')
const start=qa.indexOf('await context.addInitScript(()=>{')+'await context.addInitScript(()=>{'.length
const end=qa.indexOf('\n    })\n    const page=',start)
if(start<30||end<start)throw Error('Fixture boundaries changed')
let init=qa.slice(start,end).replaceAll('测试银行','示例股票').replaceAll('QA fixture','演示数据').replaceAll('测试来源','示例来源').replaceAll('这是隔离测试数据','演示摘要：量价活跃，需要继续核验原始公告与当日成交。').replaceAll('测试风险','研究条件可能失效；参考价不保证成交').replaceAll('测试图表','多图演示')
init=init.replace("return structuredClone(Object.hasOwn(fixed,key)?fixed[key]:[])","if(key==='SaveStockKingAIAdvice')return {ID:1};return structuredClone(Object.hasOwn(fixed,key)?fixed[key]:[])")
init=init.replace("GetStockKingAIProviders:[]","GetStockKingAIProviders:[{id:1,name:'已配置平台（演示）',model:'research-model（演示）',ready:true}]")
init=init.replace("{'aiAdvice.promptTemplates.v1':JSON.stringify([{id:'legacy',name:'我的旧模板',content:'旧提示词不能丢失'}])}","{}")
fs.mkdirSync(out,{recursive:true})
;(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true})
 try{
  const context=await browser.newContext({viewport:{width:1380,height:940},deviceScaleFactor:2})
  await context.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:5174/')?route.continue():route.abort())
  await context.addInitScript({content:`(()=>{${init}})()`})
  const page=await context.newPage(),errors=[]
  page.on('pageerror',e=>errors.push(e.message))
  const go=route=>page.goto('http://127.0.0.1:5174/#'+route,{waitUntil:'networkidle'})
  const snap=async(name,selector)=>{await page.mouse.move(0,0);await page.waitForTimeout(350);if(await page.locator('.n-message').count())await page.locator('.n-message').last().waitFor({state:'hidden',timeout:8000});await (selector?page.locator(selector):page).screenshot({path:path.join(out,name+'.png')});console.log(name)}
  await go('/king-picks');await snap('02-picks');await snap('02a-pick-card','.pick-card')
  await page.locator('.pick-why').click();await snap('03-pick-reason','.n-drawer')
  await page.keyboard.press('Escape');await page.locator('.n-drawer').waitFor({state:'hidden'})
  await page.getByRole('button',{name:'如何使用',exact:true}).click();await snap('04-pick-method','.n-drawer')
  await page.keyboard.press('Escape');await page.locator('.n-drawer').waitFor({state:'hidden'})
  await page.getByRole('button',{name:'AI 复核',exact:true}).click()
  await page.locator('.config-grid select').nth(0).selectOption({label:'已配置平台（演示）'})
  await page.locator('.config-grid select').nth(1).selectOption('1')
  await snap('05-ai-api','.ai-workspace')
  await snap('06-ai-controls','.input-panel')
  await page.locator('.template-toolbar select').selectOption('builtin-signals');await snap('07-template','.input-panel')
  await page.locator('nav.source-tabs button').filter({hasText:'研究包'}).click()
  await page.getByRole('button',{name:'生成研究包',exact:true}).click();await page.getByLabel('研究包原文').waitFor();await snap('08-export','.input-panel')
  await page.locator('nav.source-tabs button').filter({hasText:'导入报告'}).click()
  await page.locator('.import-meta input').nth(0).fill('ChatGPT 手动导入（操作示例）')
  await page.getByLabel('外部报告原文').fill('# 研究示例：先核验证据，再决定是否继续观察\n\n这是说明书演示文本，不是实际AI输出或投资建议。\n\n## 当前结论\n保持观察，暂不把规则分视为买入条件。\n\n## 支持依据\n精选快照中的成交额倍数与量比提供活跃线索；需要核对原始时点。\n\n## 反对依据\n没有完成公告核验，也没有可据此宣称胜率的样本。\n\n## 下一步\n核对最新K线、成交量及失效条件，记录复核日期。')
  await page.getByLabel('外部报告原文').evaluate(el=>el.scrollTop=0);await snap('09-import','.input-panel')
  await page.getByRole('button',{name:'保存报告',exact:true}).click();await page.locator('.report-panel .safe-markdown').waitFor();if(await page.locator('.report-panel').getByRole('button',{name:'保存',exact:true}).count())await page.locator('.report-panel').getByRole('button',{name:'保存',exact:true}).click();await snap('10-report','.research-layout')
  await go('/kline-analysis?code=600000.SH&name=示例股票');await page.mouse.move(0,0)
  await page.getByRole('button',{name:'MA 图表指标',exact:true}).click()
  await page.getByRole('button',{name:'MACD 图表指标',exact:true}).click()
  await snap('11-chart','.lw-kline-root')
  await page.getByRole('button',{name:'MA 信号说明',exact:true}).click()
  await page.getByText('公式与口径',{exact:true}).click();await snap('12-indicator','.n-drawer')
  await page.keyboard.press('Escape');await page.locator('.n-drawer').waitFor({state:'hidden'})
  await go('/multi-kline');await snap('13-multi')
  if(errors.length)throw Error(errors.join('\n'))
  fs.writeFileSync(path.join(out,'provenance.json'),JSON.stringify({version:'2.4.2',capturedAt:new Date().toISOString(),native:'01-native-picks.png is a captured installed application window. Other images are rendered production UI using isolated demo data. No API requests were made.',errors},null,2))
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
